package com.mok.entity;
// Generated 2015. 12. 3 ���� 2:29:30 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "Account", schema = "dbo", catalog = "MOK")
public class Account implements java.io.Serializable {

	private int idfAccount;
	private String userId;
	private String udid;
	private Date recentLogin;
	private char state;
	private Date regDate;

	public Account() {
	}

	public Account(int idfAccount, String userId, String udid, Date recentLogin, char state, Date regDate) {
		this.idfAccount = idfAccount;
		this.userId = userId;
		this.udid = udid;
		this.recentLogin = recentLogin;
		this.state = state;
		this.regDate = regDate;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "IDF_Account", unique = true, nullable = false)
	public int getIdfAccount() {
		return this.idfAccount;
	}

	public void setIdfAccount(int idfAccount) {
		this.idfAccount = idfAccount;
	}

	@Column(name = "UserId", nullable = false, length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "UDID", nullable = false, length = 50)
	public String getUdid() {
		return this.udid;
	}

	public void setUdid(String udid) {
		this.udid = udid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RecentLogin", nullable = false, length = 23)
	public Date getRecentLogin() {
		return this.recentLogin;
	}

	public void setRecentLogin(Date recentLogin) {
		this.recentLogin = recentLogin;
	}

	@Column(name = "State", nullable = false, length = 1)
	public char getState() {
		return this.state;
	}

	public void setState(char state) {
		this.state = state;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegDate", nullable = false, length = 23)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
