package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Branch generated by hbm2java
 */
@Entity
@Table(name = "Branch", schema = "dbo", catalog = "MOK")
public class Branch implements java.io.Serializable {

	private int idfBranch;
	private String name;
	private char type;
	private short level;
	private short offensePower;
	private short defensePower1;
	private short defensePower2;
	private short defensePower3;
	private short hp;
	private short transportPower;
	private short speed;
	private short cost;
	private short addCombatPower;
	private short addExp;
	private char offenseFormType;
	private byte offensePosition;
	private byte defensePosition;
	private byte offenseRange;
	private String damageRatePerOffenseRange;
	private byte damageRange;
	private String damageRatePerDamageRange;
	private Date regDate;
	private Set<EnemyUnitBranch> enemyUnitBranches = new HashSet<EnemyUnitBranch>(0);
	private Set<LordBranch> lordBranches = new HashSet<LordBranch>(0);
	private Cure cure;
	private Set<Training> trainings = new HashSet<Training>(0);

	public Branch() {
	}

	public Branch(int idfBranch, String name, char type, short level, short offensePower, short defensePower1,
			short defensePower2, short defensePower3, short hp, short transportPower, short speed, short cost,
			short addCombatPower, short addExp, char offenseFormType, byte offensePosition, byte defensePosition,
			byte offenseRange, String damageRatePerOffenseRange, byte damageRange, String damageRatePerDamageRange,
			Date regDate) {
		this.idfBranch = idfBranch;
		this.name = name;
		this.type = type;
		this.level = level;
		this.offensePower = offensePower;
		this.defensePower1 = defensePower1;
		this.defensePower2 = defensePower2;
		this.defensePower3 = defensePower3;
		this.hp = hp;
		this.transportPower = transportPower;
		this.speed = speed;
		this.cost = cost;
		this.addCombatPower = addCombatPower;
		this.addExp = addExp;
		this.offenseFormType = offenseFormType;
		this.offensePosition = offensePosition;
		this.defensePosition = defensePosition;
		this.offenseRange = offenseRange;
		this.damageRatePerOffenseRange = damageRatePerOffenseRange;
		this.damageRange = damageRange;
		this.damageRatePerDamageRange = damageRatePerDamageRange;
		this.regDate = regDate;
	}

	public Branch(int idfBranch, String name, char type, short level, short offensePower, short defensePower1,
			short defensePower2, short defensePower3, short hp, short transportPower, short speed, short cost,
			short addCombatPower, short addExp, char offenseFormType, byte offensePosition, byte defensePosition,
			byte offenseRange, String damageRatePerOffenseRange, byte damageRange, String damageRatePerDamageRange,
			Date regDate, Set<EnemyUnitBranch> enemyUnitBranches, Set<LordBranch> lordBranches, Cure cure,
			Set<Training> trainings) {
		this.idfBranch = idfBranch;
		this.name = name;
		this.type = type;
		this.level = level;
		this.offensePower = offensePower;
		this.defensePower1 = defensePower1;
		this.defensePower2 = defensePower2;
		this.defensePower3 = defensePower3;
		this.hp = hp;
		this.transportPower = transportPower;
		this.speed = speed;
		this.cost = cost;
		this.addCombatPower = addCombatPower;
		this.addExp = addExp;
		this.offenseFormType = offenseFormType;
		this.offensePosition = offensePosition;
		this.defensePosition = defensePosition;
		this.offenseRange = offenseRange;
		this.damageRatePerOffenseRange = damageRatePerOffenseRange;
		this.damageRange = damageRange;
		this.damageRatePerDamageRange = damageRatePerDamageRange;
		this.regDate = regDate;
		this.enemyUnitBranches = enemyUnitBranches;
		this.lordBranches = lordBranches;
		this.cure = cure;
		this.trainings = trainings;
	}

	@Id

	@Column(name = "IDF_Branch", unique = true, nullable = false)
	public int getIdfBranch() {
		return this.idfBranch;
	}

	public void setIdfBranch(int idfBranch) {
		this.idfBranch = idfBranch;
	}

	@Column(name = "Name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Type", nullable = false, length = 1)
	public char getType() {
		return this.type;
	}

	public void setType(char type) {
		this.type = type;
	}

	@Column(name = "Level", nullable = false)
	public short getLevel() {
		return this.level;
	}

	public void setLevel(short level) {
		this.level = level;
	}

	@Column(name = "OffensePower", nullable = false)
	public short getOffensePower() {
		return this.offensePower;
	}

	public void setOffensePower(short offensePower) {
		this.offensePower = offensePower;
	}

	@Column(name = "DefensePower1", nullable = false)
	public short getDefensePower1() {
		return this.defensePower1;
	}

	public void setDefensePower1(short defensePower1) {
		this.defensePower1 = defensePower1;
	}

	@Column(name = "DefensePower2", nullable = false)
	public short getDefensePower2() {
		return this.defensePower2;
	}

	public void setDefensePower2(short defensePower2) {
		this.defensePower2 = defensePower2;
	}

	@Column(name = "DefensePower3", nullable = false)
	public short getDefensePower3() {
		return this.defensePower3;
	}

	public void setDefensePower3(short defensePower3) {
		this.defensePower3 = defensePower3;
	}

	@Column(name = "HP", nullable = false)
	public short getHp() {
		return this.hp;
	}

	public void setHp(short hp) {
		this.hp = hp;
	}

	@Column(name = "TransportPower", nullable = false)
	public short getTransportPower() {
		return this.transportPower;
	}

	public void setTransportPower(short transportPower) {
		this.transportPower = transportPower;
	}

	@Column(name = "Speed", nullable = false)
	public short getSpeed() {
		return this.speed;
	}

	public void setSpeed(short speed) {
		this.speed = speed;
	}

	@Column(name = "Cost", nullable = false)
	public short getCost() {
		return this.cost;
	}

	public void setCost(short cost) {
		this.cost = cost;
	}

	@Column(name = "AddCombatPower", nullable = false)
	public short getAddCombatPower() {
		return this.addCombatPower;
	}

	public void setAddCombatPower(short addCombatPower) {
		this.addCombatPower = addCombatPower;
	}

	@Column(name = "AddEXP", nullable = false)
	public short getAddExp() {
		return this.addExp;
	}

	public void setAddExp(short addExp) {
		this.addExp = addExp;
	}

	@Column(name = "OffenseFormType", nullable = false, length = 1)
	public char getOffenseFormType() {
		return this.offenseFormType;
	}

	public void setOffenseFormType(char offenseFormType) {
		this.offenseFormType = offenseFormType;
	}

	@Column(name = "OffensePosition", nullable = false)
	public byte getOffensePosition() {
		return this.offensePosition;
	}

	public void setOffensePosition(byte offensePosition) {
		this.offensePosition = offensePosition;
	}

	@Column(name = "DefensePosition", nullable = false)
	public byte getDefensePosition() {
		return this.defensePosition;
	}

	public void setDefensePosition(byte defensePosition) {
		this.defensePosition = defensePosition;
	}

	@Column(name = "OffenseRange", nullable = false)
	public byte getOffenseRange() {
		return this.offenseRange;
	}

	public void setOffenseRange(byte offenseRange) {
		this.offenseRange = offenseRange;
	}

	@Column(name = "DamageRatePerOffenseRange", nullable = false, length = 50)
	public String getDamageRatePerOffenseRange() {
		return this.damageRatePerOffenseRange;
	}

	public void setDamageRatePerOffenseRange(String damageRatePerOffenseRange) {
		this.damageRatePerOffenseRange = damageRatePerOffenseRange;
	}

	@Column(name = "DamageRange", nullable = false)
	public byte getDamageRange() {
		return this.damageRange;
	}

	public void setDamageRange(byte damageRange) {
		this.damageRange = damageRange;
	}

	@Column(name = "DamageRatePerDamageRange", nullable = false, length = 50)
	public String getDamageRatePerDamageRange() {
		return this.damageRatePerDamageRange;
	}

	public void setDamageRatePerDamageRange(String damageRatePerDamageRange) {
		this.damageRatePerDamageRange = damageRatePerDamageRange;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegDate", nullable = false, length = 23)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branch")
	public Set<EnemyUnitBranch> getEnemyUnitBranches() {
		return this.enemyUnitBranches;
	}

	public void setEnemyUnitBranches(Set<EnemyUnitBranch> enemyUnitBranches) {
		this.enemyUnitBranches = enemyUnitBranches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branch")
	public Set<LordBranch> getLordBranches() {
		return this.lordBranches;
	}

	public void setLordBranches(Set<LordBranch> lordBranches) {
		this.lordBranches = lordBranches;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "branch")
	public Cure getCure() {
		return this.cure;
	}

	public void setCure(Cure cure) {
		this.cure = cure;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "branch")
	public Set<Training> getTrainings() {
		return this.trainings;
	}

	public void setTrainings(Set<Training> trainings) {
		this.trainings = trainings;
	}

}
