package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CellTile generated by hbm2java
 */
@Entity
@Table(name = "Cell_Tile", schema = "dbo", catalog = "MOK")
public class CellTile implements java.io.Serializable {

	private int idfCellTile;
	private Continent continent;
	private Tile tile;
	private short xpoint;
	private short ypoint;
	private short regionNum;
	private Date regDate;
	private Set<MapObjectCell> mapObjectCells = new HashSet<MapObjectCell>(0);

	public CellTile() {
	}

	public CellTile(int idfCellTile, Continent continent, Tile tile, short xpoint, short ypoint, short regionNum,
			Date regDate) {
		this.idfCellTile = idfCellTile;
		this.continent = continent;
		this.tile = tile;
		this.xpoint = xpoint;
		this.ypoint = ypoint;
		this.regionNum = regionNum;
		this.regDate = regDate;
	}

	public CellTile(int idfCellTile, Continent continent, Tile tile, short xpoint, short ypoint, short regionNum,
			Date regDate, Set<MapObjectCell> mapObjectCells) {
		this.idfCellTile = idfCellTile;
		this.continent = continent;
		this.tile = tile;
		this.xpoint = xpoint;
		this.ypoint = ypoint;
		this.regionNum = regionNum;
		this.regDate = regDate;
		this.mapObjectCells = mapObjectCells;
	}

	@Id

	@Column(name = "IDF_Cell_Tile", unique = true, nullable = false)
	public int getIdfCellTile() {
		return this.idfCellTile;
	}

	public void setIdfCellTile(int idfCellTile) {
		this.idfCellTile = idfCellTile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDF_Continent", nullable = false)
	public Continent getContinent() {
		return this.continent;
	}

	public void setContinent(Continent continent) {
		this.continent = continent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDF_Tile", nullable = false)
	public Tile getTile() {
		return this.tile;
	}

	public void setTile(Tile tile) {
		this.tile = tile;
	}

	@Column(name = "XPoint", nullable = false)
	public short getXpoint() {
		return this.xpoint;
	}

	public void setXpoint(short xpoint) {
		this.xpoint = xpoint;
	}

	@Column(name = "YPoint", nullable = false)
	public short getYpoint() {
		return this.ypoint;
	}

	public void setYpoint(short ypoint) {
		this.ypoint = ypoint;
	}

	@Column(name = "RegionNum", nullable = false)
	public short getRegionNum() {
		return this.regionNum;
	}

	public void setRegionNum(short regionNum) {
		this.regionNum = regionNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegDate", nullable = false, length = 23)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cellTile")
	public Set<MapObjectCell> getMapObjectCells() {
		return this.mapObjectCells;
	}

	public void setMapObjectCells(Set<MapObjectCell> mapObjectCells) {
		this.mapObjectCells = mapObjectCells;
	}

}
