package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Continent generated by hbm2java
 */
@Entity
@Table(name = "Continent", schema = "dbo", catalog = "MOK")
public class Continent implements java.io.Serializable {

	private int idfContinent;
	private String name;
	private Date regDate;
	private Set<CellTile> cellTiles = new HashSet<CellTile>(0);

	public Continent() {
	}

	public Continent(int idfContinent, String name, Date regDate) {
		this.idfContinent = idfContinent;
		this.name = name;
		this.regDate = regDate;
	}

	public Continent(int idfContinent, String name, Date regDate, Set<CellTile> cellTiles) {
		this.idfContinent = idfContinent;
		this.name = name;
		this.regDate = regDate;
		this.cellTiles = cellTiles;
	}

	@Id

	@Column(name = "IDF_Continent", unique = true, nullable = false)
	public int getIdfContinent() {
		return this.idfContinent;
	}

	public void setIdfContinent(int idfContinent) {
		this.idfContinent = idfContinent;
	}

	@Column(name = "Name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegDate", nullable = false, length = 23)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "continent")
	public Set<CellTile> getCellTiles() {
		return this.cellTiles;
	}

	public void setCellTiles(Set<CellTile> cellTiles) {
		this.cellTiles = cellTiles;
	}

}
