package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Coupon generated by hbm2java
 */
@Entity
@Table(name = "Coupon", schema = "dbo", catalog = "MOK")
public class Coupon implements java.io.Serializable {

	private int idfCoupon;
	private GiftSet giftSet;
	private String name;
	private String description;
	private String expiryDate;
	private String code;
	private Date regDate;

	public Coupon() {
	}

	public Coupon(int idfCoupon, GiftSet giftSet, String name, String description, String expiryDate, String code,
			Date regDate) {
		this.idfCoupon = idfCoupon;
		this.giftSet = giftSet;
		this.name = name;
		this.description = description;
		this.expiryDate = expiryDate;
		this.code = code;
		this.regDate = regDate;
	}

	@Id

	@Column(name = "IDF_Coupon", unique = true, nullable = false)
	public int getIdfCoupon() {
		return this.idfCoupon;
	}

	public void setIdfCoupon(int idfCoupon) {
		this.idfCoupon = idfCoupon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDF_GiftSet", nullable = false)
	public GiftSet getGiftSet() {
		return this.giftSet;
	}

	public void setGiftSet(GiftSet giftSet) {
		this.giftSet = giftSet;
	}

	@Column(name = "Name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description", nullable = false, length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ExpiryDate", nullable = false, length = 10)
	public String getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(String expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "Code", nullable = false, length = 36)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegDate", nullable = false, length = 23)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
