package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EnemyUnitBranchId generated by hbm2java
 */
@Embeddable
public class EnemyUnitBranchId implements java.io.Serializable {

	private int idfEnemyUnit;
	private int idfEnemyUnitBranch;

	public EnemyUnitBranchId() {
	}

	public EnemyUnitBranchId(int idfEnemyUnit, int idfEnemyUnitBranch) {
		this.idfEnemyUnit = idfEnemyUnit;
		this.idfEnemyUnitBranch = idfEnemyUnitBranch;
	}

	@Column(name = "IDF_EnemyUnit", nullable = false)
	public int getIdfEnemyUnit() {
		return this.idfEnemyUnit;
	}

	public void setIdfEnemyUnit(int idfEnemyUnit) {
		this.idfEnemyUnit = idfEnemyUnit;
	}

	@Column(name = "IDF_EnemyUnit_Branch", nullable = false)
	public int getIdfEnemyUnitBranch() {
		return this.idfEnemyUnitBranch;
	}

	public void setIdfEnemyUnitBranch(int idfEnemyUnitBranch) {
		this.idfEnemyUnitBranch = idfEnemyUnitBranch;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EnemyUnitBranchId))
			return false;
		EnemyUnitBranchId castOther = (EnemyUnitBranchId) other;

		return (this.getIdfEnemyUnit() == castOther.getIdfEnemyUnit())
				&& (this.getIdfEnemyUnitBranch() == castOther.getIdfEnemyUnitBranch());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdfEnemyUnit();
		result = 37 * result + this.getIdfEnemyUnitBranch();
		return result;
	}

}
