package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EnemyUnit generated by hbm2java
 */
@Entity
@Table(name = "EnemyUnit", schema = "dbo", catalog = "MOK")
public class EnemyUnit implements java.io.Serializable {

	private int idfEnemyUnit;
	private String name;
	private short level;
	private Date regDate;
	private Set<EnemyUnitBranch> enemyUnitBranches = new HashSet<EnemyUnitBranch>(0);

	public EnemyUnit() {
	}

	public EnemyUnit(int idfEnemyUnit, String name, short level, Date regDate) {
		this.idfEnemyUnit = idfEnemyUnit;
		this.name = name;
		this.level = level;
		this.regDate = regDate;
	}

	public EnemyUnit(int idfEnemyUnit, String name, short level, Date regDate, Set<EnemyUnitBranch> enemyUnitBranches) {
		this.idfEnemyUnit = idfEnemyUnit;
		this.name = name;
		this.level = level;
		this.regDate = regDate;
		this.enemyUnitBranches = enemyUnitBranches;
	}

	@Id

	@Column(name = "IDF_EnemyUnit", unique = true, nullable = false)
	public int getIdfEnemyUnit() {
		return this.idfEnemyUnit;
	}

	public void setIdfEnemyUnit(int idfEnemyUnit) {
		this.idfEnemyUnit = idfEnemyUnit;
	}

	@Column(name = "Name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Level", nullable = false)
	public short getLevel() {
		return this.level;
	}

	public void setLevel(short level) {
		this.level = level;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegDate", nullable = false, length = 23)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enemyUnit")
	public Set<EnemyUnitBranch> getEnemyUnitBranches() {
		return this.enemyUnitBranches;
	}

	public void setEnemyUnitBranches(Set<EnemyUnitBranch> enemyUnitBranches) {
		this.enemyUnitBranches = enemyUnitBranches;
	}

}
