package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GiftSetItem generated by hbm2java
 */
@Entity
@Table(name = "GiftSet_Item", schema = "dbo", catalog = "MOK")
public class GiftSetItem implements java.io.Serializable {

	private int idfGiftSetItem;
	private GiftSet giftSet;
	private Item item;
	private short quantity;
	private Date regDate;
	private Set<InvenItem> invenItems = new HashSet<InvenItem>(0);

	public GiftSetItem() {
	}

	public GiftSetItem(int idfGiftSetItem, GiftSet giftSet, Item item, short quantity, Date regDate) {
		this.idfGiftSetItem = idfGiftSetItem;
		this.giftSet = giftSet;
		this.item = item;
		this.quantity = quantity;
		this.regDate = regDate;
	}

	public GiftSetItem(int idfGiftSetItem, GiftSet giftSet, Item item, short quantity, Date regDate,
			Set<InvenItem> invenItems) {
		this.idfGiftSetItem = idfGiftSetItem;
		this.giftSet = giftSet;
		this.item = item;
		this.quantity = quantity;
		this.regDate = regDate;
		this.invenItems = invenItems;
	}

	@Id

	@Column(name = "IDF_GiftSet_Item", unique = true, nullable = false)
	public int getIdfGiftSetItem() {
		return this.idfGiftSetItem;
	}

	public void setIdfGiftSetItem(int idfGiftSetItem) {
		this.idfGiftSetItem = idfGiftSetItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDF_GiftSet", nullable = false)
	public GiftSet getGiftSet() {
		return this.giftSet;
	}

	public void setGiftSet(GiftSet giftSet) {
		this.giftSet = giftSet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDF_Item", nullable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@Column(name = "Quantity", nullable = false)
	public short getQuantity() {
		return this.quantity;
	}

	public void setQuantity(short quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegDate", nullable = false, length = 23)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "giftSetItem")
	public Set<InvenItem> getInvenItems() {
		return this.invenItems;
	}

	public void setInvenItems(Set<InvenItem> invenItems) {
		this.invenItems = invenItems;
	}

}
