package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvenMaterial generated by hbm2java
 */
@Entity
@Table(name = "Inven_Material", schema = "dbo", catalog = "MOK")
public class InvenMaterial implements java.io.Serializable {

	private InvenMaterialId id;
	private Lord lord;
	private Material material;
	private Date regDate;

	public InvenMaterial() {
	}

	public InvenMaterial(InvenMaterialId id, Lord lord, Material material, Date regDate) {
		this.id = id;
		this.lord = lord;
		this.material = material;
		this.regDate = regDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idfAccount", column = @Column(name = "IDF_Account", nullable = false) ),
			@AttributeOverride(name = "idfInvenMaterial", column = @Column(name = "IDF_Inven_Material", nullable = false) ) })
	public InvenMaterialId getId() {
		return this.id;
	}

	public void setId(InvenMaterialId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDF_Account", nullable = false, insertable = false, updatable = false)
	public Lord getLord() {
		return this.lord;
	}

	public void setLord(Lord lord) {
		this.lord = lord;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDF_Material", nullable = false)
	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegDate", nullable = false, length = 23)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
