package com.mok.entity;
// Generated 2015. 11. 25 ���� 7:29:01 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvenWeaponId generated by hbm2java
 */
@Embeddable
public class InvenWeaponId implements java.io.Serializable {

	private int idfLord;
	private int idfInvenWeapon;

	public InvenWeaponId() {
	}

	public InvenWeaponId(int idfLord, int idfInvenWeapon) {
		this.idfLord = idfLord;
		this.idfInvenWeapon = idfInvenWeapon;
	}

	@Column(name = "idf_lord", nullable = false)
	public int getIdfLord() {
		return this.idfLord;
	}

	public void setIdfLord(int idfLord) {
		this.idfLord = idfLord;
	}

	@Column(name = "idf_inven_weapon", nullable = false)
	public int getIdfInvenWeapon() {
		return this.idfInvenWeapon;
	}

	public void setIdfInvenWeapon(int idfInvenWeapon) {
		this.idfInvenWeapon = idfInvenWeapon;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvenWeaponId))
			return false;
		InvenWeaponId castOther = (InvenWeaponId) other;

		return (this.getIdfLord() == castOther.getIdfLord())
				&& (this.getIdfInvenWeapon() == castOther.getIdfInvenWeapon());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdfLord();
		result = 37 * result + this.getIdfInvenWeapon();
		return result;
	}

}
