package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvenMaterialId generated by hbm2java
 */
@Embeddable
public class InvenMaterialId implements java.io.Serializable {

	private int idfAccount;
	private int idfInvenMaterial;

	public InvenMaterialId() {
	}

	public InvenMaterialId(int idfAccount, int idfInvenMaterial) {
		this.idfAccount = idfAccount;
		this.idfInvenMaterial = idfInvenMaterial;
	}

	@Column(name = "IDF_Account", nullable = false)
	public int getIdfAccount() {
		return this.idfAccount;
	}

	public void setIdfAccount(int idfAccount) {
		this.idfAccount = idfAccount;
	}

	@Column(name = "IDF_Inven_Material", nullable = false)
	public int getIdfInvenMaterial() {
		return this.idfInvenMaterial;
	}

	public void setIdfInvenMaterial(int idfInvenMaterial) {
		this.idfInvenMaterial = idfInvenMaterial;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvenMaterialId))
			return false;
		InvenMaterialId castOther = (InvenMaterialId) other;

		return (this.getIdfAccount() == castOther.getIdfAccount())
				&& (this.getIdfInvenMaterial() == castOther.getIdfInvenMaterial());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdfAccount();
		result = 37 * result + this.getIdfInvenMaterial();
		return result;
	}

}
