package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvenItem generated by hbm2java
 */
@Entity
@Table(name = "Inven_Item", schema = "dbo", catalog = "MOK")
public class InvenItem implements java.io.Serializable {

	private InvenItemId id;
	private GiftSetItem giftSetItem;
	private Item item;
	private Lord lord;
	private short quantity;
	private char type;
	private Date regDate;

	public InvenItem() {
	}

	public InvenItem(InvenItemId id, GiftSetItem giftSetItem, Item item, Lord lord, short quantity, char type,
			Date regDate) {
		this.id = id;
		this.giftSetItem = giftSetItem;
		this.item = item;
		this.lord = lord;
		this.quantity = quantity;
		this.type = type;
		this.regDate = regDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idfAccount", column = @Column(name = "IDF_Account", nullable = false) ),
			@AttributeOverride(name = "idfInvenItem", column = @Column(name = "IDF_Inven_Item", nullable = false) ) })
	public InvenItemId getId() {
		return this.id;
	}

	public void setId(InvenItemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDF_GiftSet_Item", nullable = false)
	public GiftSetItem getGiftSetItem() {
		return this.giftSetItem;
	}

	public void setGiftSetItem(GiftSetItem giftSetItem) {
		this.giftSetItem = giftSetItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDF_Item", nullable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDF_Account", nullable = false, insertable = false, updatable = false)
	public Lord getLord() {
		return this.lord;
	}

	public void setLord(Lord lord) {
		this.lord = lord;
	}

	@Column(name = "Quantity", nullable = false)
	public short getQuantity() {
		return this.quantity;
	}

	public void setQuantity(short quantity) {
		this.quantity = quantity;
	}

	@Column(name = "Type", nullable = false, length = 1)
	public char getType() {
		return this.type;
	}

	public void setType(char type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegDate", nullable = false, length = 23)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
