package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LordBranch generated by hbm2java
 */
@Entity
@Table(name = "Lord_Branch", schema = "dbo", catalog = "MOK")
public class LordBranch implements java.io.Serializable {

	private LordBranchId id;
	private Branch branch;
	private Lord lord;
	private int quantity;
	private Date regDate;

	public LordBranch() {
	}

	public LordBranch(LordBranchId id, Branch branch, Lord lord, int quantity, Date regDate) {
		this.id = id;
		this.branch = branch;
		this.lord = lord;
		this.quantity = quantity;
		this.regDate = regDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idfAccount", column = @Column(name = "IDF_Account", nullable = false) ),
			@AttributeOverride(name = "idfLordBranch", column = @Column(name = "IDF_Lord_Branch", nullable = false) ) })
	public LordBranchId getId() {
		return this.id;
	}

	public void setId(LordBranchId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDF_Branch", nullable = false)
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDF_Account", nullable = false, insertable = false, updatable = false)
	public Lord getLord() {
		return this.lord;
	}

	public void setLord(Lord lord) {
		this.lord = lord;
	}

	@Column(name = "Quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegDate", nullable = false, length = 23)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
