package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LordBranchId generated by hbm2java
 */
@Embeddable
public class LordBranchId implements java.io.Serializable {

	private int idfAccount;
	private int idfLordBranch;

	public LordBranchId() {
	}

	public LordBranchId(int idfAccount, int idfLordBranch) {
		this.idfAccount = idfAccount;
		this.idfLordBranch = idfLordBranch;
	}

	@Column(name = "IDF_Account", nullable = false)
	public int getIdfAccount() {
		return this.idfAccount;
	}

	public void setIdfAccount(int idfAccount) {
		this.idfAccount = idfAccount;
	}

	@Column(name = "IDF_Lord_Branch", nullable = false)
	public int getIdfLordBranch() {
		return this.idfLordBranch;
	}

	public void setIdfLordBranch(int idfLordBranch) {
		this.idfLordBranch = idfLordBranch;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LordBranchId))
			return false;
		LordBranchId castOther = (LordBranchId) other;

		return (this.getIdfAccount() == castOther.getIdfAccount())
				&& (this.getIdfLordBranch() == castOther.getIdfLordBranch());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdfAccount();
		result = 37 * result + this.getIdfLordBranch();
		return result;
	}

}
