package com.mok.entity;
// Generated 2015. 12. 3 ���� 2:27:33 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lord generated by hbm2java
 */
@Entity
@Table(name = "Lord", schema = "dbo", catalog = "MOK")
public class Lord implements java.io.Serializable {

	private int idfAccount;
	private String name;
	private String title;
	private String language;
	private String nation;
	private int food;
	private int wood;
	private int stone;
	private int gold;
	private byte confidenceGrade;
	private byte activityPower;
	private long exp;
	private Date regDate;

	public Lord() {
	}

	public Lord(int idfAccount, String name, String title, String language, String nation, int food, int wood,
			int stone, int gold, byte confidenceGrade, byte activityPower, long exp, Date regDate) {
		this.idfAccount = idfAccount;
		this.name = name;
		this.title = title;
		this.language = language;
		this.nation = nation;
		this.food = food;
		this.wood = wood;
		this.stone = stone;
		this.gold = gold;
		this.confidenceGrade = confidenceGrade;
		this.activityPower = activityPower;
		this.exp = exp;
		this.regDate = regDate;
	}

	@Id

	@Column(name = "IDF_Account", unique = true, nullable = false)
	public int getIdfAccount() {
		return this.idfAccount;
	}

	public void setIdfAccount(int idfAccount) {
		this.idfAccount = idfAccount;
	}

	@Column(name = "Name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Title", nullable = false, length = 20)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Language", nullable = false, length = 20)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "Nation", nullable = false, length = 20)
	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	@Column(name = "Food", nullable = false)
	public int getFood() {
		return this.food;
	}

	public void setFood(int food) {
		this.food = food;
	}

	@Column(name = "Wood", nullable = false)
	public int getWood() {
		return this.wood;
	}

	public void setWood(int wood) {
		this.wood = wood;
	}

	@Column(name = "Stone", nullable = false)
	public int getStone() {
		return this.stone;
	}

	public void setStone(int stone) {
		this.stone = stone;
	}

	@Column(name = "Gold", nullable = false)
	public int getGold() {
		return this.gold;
	}

	public void setGold(int gold) {
		this.gold = gold;
	}

	@Column(name = "ConfidenceGrade", nullable = false)
	public byte getConfidenceGrade() {
		return this.confidenceGrade;
	}

	public void setConfidenceGrade(byte confidenceGrade) {
		this.confidenceGrade = confidenceGrade;
	}

	@Column(name = "ActivityPower", nullable = false)
	public byte getActivityPower() {
		return this.activityPower;
	}

	public void setActivityPower(byte activityPower) {
		this.activityPower = activityPower;
	}

	@Column(name = "EXP", nullable = false)
	public long getExp() {
		return this.exp;
	}

	public void setExp(long exp) {
		this.exp = exp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegDate", nullable = false, length = 23)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
