package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MapObjectCell generated by hbm2java
 */
@Entity
@Table(name = "MapObject_Cell", schema = "dbo", catalog = "MOK")
public class MapObjectCell implements java.io.Serializable {

	private int idfMapObjectCell;
	private CellTile cellTile;
	private MapObject mapObject;
	private Integer quantityStatus;
	private Date regDate;

	public MapObjectCell() {
	}

	public MapObjectCell(int idfMapObjectCell, CellTile cellTile, MapObject mapObject, Date regDate) {
		this.idfMapObjectCell = idfMapObjectCell;
		this.cellTile = cellTile;
		this.mapObject = mapObject;
		this.regDate = regDate;
	}

	public MapObjectCell(int idfMapObjectCell, CellTile cellTile, MapObject mapObject, Integer quantityStatus,
			Date regDate) {
		this.idfMapObjectCell = idfMapObjectCell;
		this.cellTile = cellTile;
		this.mapObject = mapObject;
		this.quantityStatus = quantityStatus;
		this.regDate = regDate;
	}

	@Id

	@Column(name = "IDF_MapObject_Cell", unique = true, nullable = false)
	public int getIdfMapObjectCell() {
		return this.idfMapObjectCell;
	}

	public void setIdfMapObjectCell(int idfMapObjectCell) {
		this.idfMapObjectCell = idfMapObjectCell;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDF_Cell_Tile", nullable = false)
	public CellTile getCellTile() {
		return this.cellTile;
	}

	public void setCellTile(CellTile cellTile) {
		this.cellTile = cellTile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDF_MapObject", nullable = false)
	public MapObject getMapObject() {
		return this.mapObject;
	}

	public void setMapObject(MapObject mapObject) {
		this.mapObject = mapObject;
	}

	@Column(name = "QuantityStatus")
	public Integer getQuantityStatus() {
		return this.quantityStatus;
	}

	public void setQuantityStatus(Integer quantityStatus) {
		this.quantityStatus = quantityStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegDate", nullable = false, length = 23)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
