package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MapObject generated by hbm2java
 */
@Entity
@Table(name = "MapObject", schema = "dbo", catalog = "MOK")
public class MapObject implements java.io.Serializable {

	private int idfMapObject;
	private String name;
	private char type;
	private short level;
	private int quantity;
	private Date regDate;
	private Set<MapObjectCell> mapObjectCells = new HashSet<MapObjectCell>(0);

	public MapObject() {
	}

	public MapObject(int idfMapObject, String name, char type, short level, int quantity, Date regDate) {
		this.idfMapObject = idfMapObject;
		this.name = name;
		this.type = type;
		this.level = level;
		this.quantity = quantity;
		this.regDate = regDate;
	}

	public MapObject(int idfMapObject, String name, char type, short level, int quantity, Date regDate,
			Set<MapObjectCell> mapObjectCells) {
		this.idfMapObject = idfMapObject;
		this.name = name;
		this.type = type;
		this.level = level;
		this.quantity = quantity;
		this.regDate = regDate;
		this.mapObjectCells = mapObjectCells;
	}

	@Id

	@Column(name = "IDF_MapObject", unique = true, nullable = false)
	public int getIdfMapObject() {
		return this.idfMapObject;
	}

	public void setIdfMapObject(int idfMapObject) {
		this.idfMapObject = idfMapObject;
	}

	@Column(name = "Name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Type", nullable = false, length = 1)
	public char getType() {
		return this.type;
	}

	public void setType(char type) {
		this.type = type;
	}

	@Column(name = "Level", nullable = false)
	public short getLevel() {
		return this.level;
	}

	public void setLevel(short level) {
		this.level = level;
	}

	@Column(name = "Quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegDate", nullable = false, length = 23)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mapObject")
	public Set<MapObjectCell> getMapObjectCells() {
		return this.mapObjectCells;
	}

	public void setMapObjectCells(Set<MapObjectCell> mapObjectCells) {
		this.mapObjectCells = mapObjectCells;
	}

}
