package com.mok.entity;
// Generated 2015. 11. 25 ���� 7:29:01 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MapObjectRegion generated by hbm2java
 */
@Entity
@Table(name = "map_object_region", schema = "public")
public class MapObjectRegion implements java.io.Serializable {

	private int idfObjectRegion;
	private RegionTile regionTile;
	private MapObject mapObject;
	private long quantityStatus;
	private Date regDate;

	public MapObjectRegion() {
	}

	public MapObjectRegion(int idfObjectRegion, RegionTile regionTile, MapObject mapObject, long quantityStatus,
			Date regDate) {
		this.idfObjectRegion = idfObjectRegion;
		this.regionTile = regionTile;
		this.mapObject = mapObject;
		this.quantityStatus = quantityStatus;
		this.regDate = regDate;
	}

	@Id

	@Column(name = "idf_object_region", unique = true, nullable = false)
	public int getIdfObjectRegion() {
		return this.idfObjectRegion;
	}

	public void setIdfObjectRegion(int idfObjectRegion) {
		this.idfObjectRegion = idfObjectRegion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_region_tile", nullable = false)
	public RegionTile getRegionTile() {
		return this.regionTile;
	}

	public void setRegionTile(RegionTile regionTile) {
		this.regionTile = regionTile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_map_object", nullable = false)
	public MapObject getMapObject() {
		return this.mapObject;
	}

	public void setMapObject(MapObject mapObject) {
		this.mapObject = mapObject;
	}

	@Column(name = "quantity_status", nullable = false)
	public long getQuantityStatus() {
		return this.quantityStatus;
	}

	public void setQuantityStatus(long quantityStatus) {
		this.quantityStatus = quantityStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 29)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
