package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Material generated by hbm2java
 */
@Entity
@Table(name = "Material", schema = "dbo", catalog = "MOK")
public class Material implements java.io.Serializable {

	private int idfMaterial;
	private String name;
	private int price;
	private Date regDate;
	private Set<InvenMaterial> invenMaterials = new HashSet<InvenMaterial>(0);

	public Material() {
	}

	public Material(int idfMaterial, String name, int price, Date regDate) {
		this.idfMaterial = idfMaterial;
		this.name = name;
		this.price = price;
		this.regDate = regDate;
	}

	public Material(int idfMaterial, String name, int price, Date regDate, Set<InvenMaterial> invenMaterials) {
		this.idfMaterial = idfMaterial;
		this.name = name;
		this.price = price;
		this.regDate = regDate;
		this.invenMaterials = invenMaterials;
	}

	@Id

	@Column(name = "IDF_Material", unique = true, nullable = false)
	public int getIdfMaterial() {
		return this.idfMaterial;
	}

	public void setIdfMaterial(int idfMaterial) {
		this.idfMaterial = idfMaterial;
	}

	@Column(name = "Name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegDate", nullable = false, length = 23)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "material")
	public Set<InvenMaterial> getInvenMaterials() {
		return this.invenMaterials;
	}

	public void setInvenMaterials(Set<InvenMaterial> invenMaterials) {
		this.invenMaterials = invenMaterials;
	}

}
