package com.mok.entity;
// Generated 2015. 11. 25 ���� 7:29:01 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Production generated by hbm2java
 */
@Entity
@Table(name = "production", schema = "public")
public class Production implements java.io.Serializable {

	private int idfProduction;
	private Structure structure;
	private Weapon weapon;
	private int productionTime;
	private String weaponName;
	private long needFood;
	private long needWood;
	private long needStone;
	private long needGold;
	private Date redDate;

	public Production() {
	}

	public Production(int idfProduction, Structure structure, Weapon weapon, int productionTime, String weaponName,
			long needFood, long needWood, long needStone, long needGold, Date redDate) {
		this.idfProduction = idfProduction;
		this.structure = structure;
		this.weapon = weapon;
		this.productionTime = productionTime;
		this.weaponName = weaponName;
		this.needFood = needFood;
		this.needWood = needWood;
		this.needStone = needStone;
		this.needGold = needGold;
		this.redDate = redDate;
	}

	@Id

	@Column(name = "idf_production", unique = true, nullable = false)
	public int getIdfProduction() {
		return this.idfProduction;
	}

	public void setIdfProduction(int idfProduction) {
		this.idfProduction = idfProduction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_structure", nullable = false)
	public Structure getStructure() {
		return this.structure;
	}

	public void setStructure(Structure structure) {
		this.structure = structure;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_weapon", nullable = false)
	public Weapon getWeapon() {
		return this.weapon;
	}

	public void setWeapon(Weapon weapon) {
		this.weapon = weapon;
	}

	@Column(name = "production_time", nullable = false)
	public int getProductionTime() {
		return this.productionTime;
	}

	public void setProductionTime(int productionTime) {
		this.productionTime = productionTime;
	}

	@Column(name = "weapon_name", nullable = false, length = 15)
	public String getWeaponName() {
		return this.weaponName;
	}

	public void setWeaponName(String weaponName) {
		this.weaponName = weaponName;
	}

	@Column(name = "need_food", nullable = false)
	public long getNeedFood() {
		return this.needFood;
	}

	public void setNeedFood(long needFood) {
		this.needFood = needFood;
	}

	@Column(name = "need_wood", nullable = false)
	public long getNeedWood() {
		return this.needWood;
	}

	public void setNeedWood(long needWood) {
		this.needWood = needWood;
	}

	@Column(name = "need_stone", nullable = false)
	public long getNeedStone() {
		return this.needStone;
	}

	public void setNeedStone(long needStone) {
		this.needStone = needStone;
	}

	@Column(name = "need_gold", nullable = false)
	public long getNeedGold() {
		return this.needGold;
	}

	public void setNeedGold(long needGold) {
		this.needGold = needGold;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "red_date", nullable = false, length = 29)
	public Date getRedDate() {
		return this.redDate;
	}

	public void setRedDate(Date redDate) {
		this.redDate = redDate;
	}

}
