package com.mok.entity;
// Generated 2015. 11. 25 ���� 7:29:01 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegionTile generated by hbm2java
 */
@Entity
@Table(name = "region_tile", schema = "public")
public class RegionTile implements java.io.Serializable {

	private int idfRegionTile;
	private Tile tile;
	private Region region;
	private short x;
	private short y;
	private Date regDate;
	private Set<MapObjectRegion> mapObjectRegions = new HashSet<MapObjectRegion>(0);

	public RegionTile() {
	}

	public RegionTile(int idfRegionTile, Tile tile, Region region, short x, short y, Date regDate) {
		this.idfRegionTile = idfRegionTile;
		this.tile = tile;
		this.region = region;
		this.x = x;
		this.y = y;
		this.regDate = regDate;
	}

	public RegionTile(int idfRegionTile, Tile tile, Region region, short x, short y, Date regDate,
			Set<MapObjectRegion> mapObjectRegions) {
		this.idfRegionTile = idfRegionTile;
		this.tile = tile;
		this.region = region;
		this.x = x;
		this.y = y;
		this.regDate = regDate;
		this.mapObjectRegions = mapObjectRegions;
	}

	@Id

	@Column(name = "idf_region_tile", unique = true, nullable = false)
	public int getIdfRegionTile() {
		return this.idfRegionTile;
	}

	public void setIdfRegionTile(int idfRegionTile) {
		this.idfRegionTile = idfRegionTile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_tile", nullable = false)
	public Tile getTile() {
		return this.tile;
	}

	public void setTile(Tile tile) {
		this.tile = tile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_region", nullable = false)
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "x", nullable = false)
	public short getX() {
		return this.x;
	}

	public void setX(short x) {
		this.x = x;
	}

	@Column(name = "y", nullable = false)
	public short getY() {
		return this.y;
	}

	public void setY(short y) {
		this.y = y;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 29)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regionTile")
	public Set<MapObjectRegion> getMapObjectRegions() {
		return this.mapObjectRegions;
	}

	public void setMapObjectRegions(Set<MapObjectRegion> mapObjectRegions) {
		this.mapObjectRegions = mapObjectRegions;
	}

}
