package com.mok.entity;
// Generated 2015. 11. 25 ���� 7:29:01 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", schema = "public")
public class Region implements java.io.Serializable {

	private int idfRegion;
	private Continent continent;
	private short x;
	private short y;
	private Date regDate;
	private Set<RegionTile> regionTiles = new HashSet<RegionTile>(0);

	public Region() {
	}

	public Region(int idfRegion, Continent continent, short x, short y, Date regDate) {
		this.idfRegion = idfRegion;
		this.continent = continent;
		this.x = x;
		this.y = y;
		this.regDate = regDate;
	}

	public Region(int idfRegion, Continent continent, short x, short y, Date regDate, Set<RegionTile> regionTiles) {
		this.idfRegion = idfRegion;
		this.continent = continent;
		this.x = x;
		this.y = y;
		this.regDate = regDate;
		this.regionTiles = regionTiles;
	}

	@Id

	@Column(name = "idf_region", unique = true, nullable = false)
	public int getIdfRegion() {
		return this.idfRegion;
	}

	public void setIdfRegion(int idfRegion) {
		this.idfRegion = idfRegion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_continent", nullable = false)
	public Continent getContinent() {
		return this.continent;
	}

	public void setContinent(Continent continent) {
		this.continent = continent;
	}

	@Column(name = "x", nullable = false)
	public short getX() {
		return this.x;
	}

	public void setX(short x) {
		this.x = x;
	}

	@Column(name = "y", nullable = false)
	public short getY() {
		return this.y;
	}

	public void setY(short y) {
		this.y = y;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 29)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<RegionTile> getRegionTiles() {
		return this.regionTiles;
	}

	public void setRegionTiles(Set<RegionTile> regionTiles) {
		this.regionTiles = regionTiles;
	}

}
