package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Structure generated by hbm2java
 */
@Entity
@Table(name = "Structure", schema = "dbo", catalog = "MOK")
public class Structure implements java.io.Serializable {

	private int idfStructure;
	private String name;
	private short level;
	private int buildTime;
	private int needFood;
	private int needWood;
	private int needStone;
	private int needGold;
	private short addCombatPower;
	private short addExp;
	private Integer capacity;
	private Byte outputPerSec;
	private Date regDate;
	private Set<Training> trainings = new HashSet<Training>(0);
	private Set<Research> researches = new HashSet<Research>(0);

	public Structure() {
	}

	public Structure(int idfStructure, String name, short level, int buildTime, int needFood, int needWood,
			int needStone, int needGold, short addCombatPower, short addExp, Date regDate) {
		this.idfStructure = idfStructure;
		this.name = name;
		this.level = level;
		this.buildTime = buildTime;
		this.needFood = needFood;
		this.needWood = needWood;
		this.needStone = needStone;
		this.needGold = needGold;
		this.addCombatPower = addCombatPower;
		this.addExp = addExp;
		this.regDate = regDate;
	}

	public Structure(int idfStructure, String name, short level, int buildTime, int needFood, int needWood,
			int needStone, int needGold, short addCombatPower, short addExp, Integer capacity, Byte outputPerSec,
			Date regDate, Set<Training> trainings, Set<Research> researches) {
		this.idfStructure = idfStructure;
		this.name = name;
		this.level = level;
		this.buildTime = buildTime;
		this.needFood = needFood;
		this.needWood = needWood;
		this.needStone = needStone;
		this.needGold = needGold;
		this.addCombatPower = addCombatPower;
		this.addExp = addExp;
		this.capacity = capacity;
		this.outputPerSec = outputPerSec;
		this.regDate = regDate;
		this.trainings = trainings;
		this.researches = researches;
	}

	@Id

	@Column(name = "IDF_Structure", unique = true, nullable = false)
	public int getIdfStructure() {
		return this.idfStructure;
	}

	public void setIdfStructure(int idfStructure) {
		this.idfStructure = idfStructure;
	}

	@Column(name = "Name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Level", nullable = false)
	public short getLevel() {
		return this.level;
	}

	public void setLevel(short level) {
		this.level = level;
	}

	@Column(name = "BuildTime", nullable = false)
	public int getBuildTime() {
		return this.buildTime;
	}

	public void setBuildTime(int buildTime) {
		this.buildTime = buildTime;
	}

	@Column(name = "NeedFood", nullable = false)
	public int getNeedFood() {
		return this.needFood;
	}

	public void setNeedFood(int needFood) {
		this.needFood = needFood;
	}

	@Column(name = "NeedWood", nullable = false)
	public int getNeedWood() {
		return this.needWood;
	}

	public void setNeedWood(int needWood) {
		this.needWood = needWood;
	}

	@Column(name = "NeedStone", nullable = false)
	public int getNeedStone() {
		return this.needStone;
	}

	public void setNeedStone(int needStone) {
		this.needStone = needStone;
	}

	@Column(name = "NeedGold", nullable = false)
	public int getNeedGold() {
		return this.needGold;
	}

	public void setNeedGold(int needGold) {
		this.needGold = needGold;
	}

	@Column(name = "AddCombatPower", nullable = false)
	public short getAddCombatPower() {
		return this.addCombatPower;
	}

	public void setAddCombatPower(short addCombatPower) {
		this.addCombatPower = addCombatPower;
	}

	@Column(name = "AddEXP", nullable = false)
	public short getAddExp() {
		return this.addExp;
	}

	public void setAddExp(short addExp) {
		this.addExp = addExp;
	}

	@Column(name = "Capacity")
	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	@Column(name = "OutputPerSec")
	public Byte getOutputPerSec() {
		return this.outputPerSec;
	}

	public void setOutputPerSec(Byte outputPerSec) {
		this.outputPerSec = outputPerSec;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegDate", nullable = false, length = 23)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "structure")
	public Set<Training> getTrainings() {
		return this.trainings;
	}

	public void setTrainings(Set<Training> trainings) {
		this.trainings = trainings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "structure")
	public Set<Research> getResearches() {
		return this.researches;
	}

	public void setResearches(Set<Research> researches) {
		this.researches = researches;
	}

}
