package com.mok.entity;
// Generated 2015. 12. 2 ���� 3:14:23 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Training generated by hbm2java
 */
@Entity
@Table(name = "Training", schema = "dbo", catalog = "MOK")
public class Training implements java.io.Serializable {

	private int idfTraining;
	private Branch branch;
	private Weapon weapon;
	private Structure structure;
	private String name;
	private short level;
	private int trainingTime;
	private int needFood;
	private int needWood;
	private int needStone;
	private int needGold;
	private Date regDate;

	public Training() {
	}

	public Training(int idfTraining, Branch branch, Structure structure, String name, short level, int trainingTime,
			int needFood, int needWood, int needStone, int needGold, Date regDate) {
		this.idfTraining = idfTraining;
		this.branch = branch;
		this.structure = structure;
		this.name = name;
		this.level = level;
		this.trainingTime = trainingTime;
		this.needFood = needFood;
		this.needWood = needWood;
		this.needStone = needStone;
		this.needGold = needGold;
		this.regDate = regDate;
	}

	@Id

	@Column(name = "IDF_Training", unique = true, nullable = false)
	public int getIdfTraining() {
		return this.idfTraining;
	}

	public void setIdfTraining(int idfTraining) {
		this.idfTraining = idfTraining;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_weapon", nullable = false)
	public Weapon getWeapon() {
		return this.weapon;
	}

	public void setWeapon(Weapon weapon) {
		this.weapon = weapon;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDF_Branch", nullable = false)
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDF_Structure", nullable = false)
	public Structure getStructure() {
		return this.structure;
	}

	public void setStructure(Structure structure) {
		this.structure = structure;
	}

	@Column(name = "Name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Level", nullable = false)
	public short getLevel() {
		return this.level;
	}

	public void setLevel(short level) {
		this.level = level;
	}

	@Column(name = "TrainingTime", nullable = false)
	public int getTrainingTime() {
		return this.trainingTime;
	}

	public void setTrainingTime(int trainingTime) {
		this.trainingTime = trainingTime;
	}

	@Column(name = "NeedFood", nullable = false)
	public int getNeedFood() {
		return this.needFood;
	}

	public void setNeedFood(int needFood) {
		this.needFood = needFood;
	}

	@Column(name = "NeedWood", nullable = false)
	public int getNeedWood() {
		return this.needWood;
	}

	public void setNeedWood(int needWood) {
		this.needWood = needWood;
	}

	@Column(name = "NeedStone", nullable = false)
	public int getNeedStone() {
		return this.needStone;
	}

	public void setNeedStone(int needStone) {
		this.needStone = needStone;
	}

	@Column(name = "NeedGold", nullable = false)
	public int getNeedGold() {
		return this.needGold;
	}

	public void setNeedGold(int needGold) {
		this.needGold = needGold;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RegDate", nullable = false, length = 23)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
