package com.mok.entity;
// Generated 2015. 11. 25 ���� 7:29:01 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Weapon generated by hbm2java
 */
@Entity
@Table(name = "weapon", schema = "public")
public class Weapon implements java.io.Serializable {

	private int idfWeapon;
	private String name;
	private char type;
	private int price;
	private Date regDate;
	private Set<InvenWeapon> invenWeapons = new HashSet<InvenWeapon>(0);
	private Set<Training> trainings = new HashSet<Training>(0);
	private Set<Production> productions = new HashSet<Production>(0);
	private Set<WeaponMaterial> weaponMaterials = new HashSet<WeaponMaterial>(0);

	public Weapon() {
	}

	public Weapon(int idfWeapon, String name, char type, int price, Date regDate) {
		this.idfWeapon = idfWeapon;
		this.name = name;
		this.type = type;
		this.price = price;
		this.regDate = regDate;
	}

	public Weapon(int idfWeapon, String name, char type, int price, Date regDate, Set<InvenWeapon> invenWeapons,
			Set<Training> trainings, Set<Production> productions, Set<WeaponMaterial> weaponMaterials) {
		this.idfWeapon = idfWeapon;
		this.name = name;
		this.type = type;
		this.price = price;
		this.regDate = regDate;
		this.invenWeapons = invenWeapons;
		this.trainings = trainings;
		this.productions = productions;
		this.weaponMaterials = weaponMaterials;
	}

	@Id

	@Column(name = "idf_weapon", unique = true, nullable = false)
	public int getIdfWeapon() {
		return this.idfWeapon;
	}

	public void setIdfWeapon(int idfWeapon) {
		this.idfWeapon = idfWeapon;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", nullable = false, length = 1)
	public char getType() {
		return this.type;
	}

	public void setType(char type) {
		this.type = type;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 29)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "weapon")
	public Set<InvenWeapon> getInvenWeapons() {
		return this.invenWeapons;
	}

	public void setInvenWeapons(Set<InvenWeapon> invenWeapons) {
		this.invenWeapons = invenWeapons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "weapon")
	public Set<Training> getTrainings() {
		return this.trainings;
	}

	public void setTrainings(Set<Training> trainings) {
		this.trainings = trainings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "weapon")
	public Set<Production> getProductions() {
		return this.productions;
	}

	public void setProductions(Set<Production> productions) {
		this.productions = productions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "weapon")
	public Set<WeaponMaterial> getWeaponMaterials() {
		return this.weaponMaterials;
	}

	public void setWeaponMaterials(Set<WeaponMaterial> weaponMaterials) {
		this.weaponMaterials = weaponMaterials;
	}

}
