package com.mok.entity;
// Generated 2015. 11. 25 ���� 7:29:01 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WeaponMaterial generated by hbm2java
 */
@Entity
@Table(name = "weapon_material", schema = "public")
public class WeaponMaterial implements java.io.Serializable {

	private WeaponMaterialId id;
	private Material material;
	private Weapon weapon;
	private short quantity;
	private Date regDate;

	public WeaponMaterial() {
	}

	public WeaponMaterial(WeaponMaterialId id, Material material, Weapon weapon, short quantity, Date regDate) {
		this.id = id;
		this.material = material;
		this.weapon = weapon;
		this.quantity = quantity;
		this.regDate = regDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idfWeapon", column = @Column(name = "idf_weapon", nullable = false) ),
			@AttributeOverride(name = "idfWeaponMaterial", column = @Column(name = "idf_weapon_material", nullable = false) ) })
	public WeaponMaterialId getId() {
		return this.id;
	}

	public void setId(WeaponMaterialId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_material", nullable = false)
	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idf_weapon", nullable = false, insertable = false, updatable = false)
	public Weapon getWeapon() {
		return this.weapon;
	}

	public void setWeapon(Weapon weapon) {
		this.weapon = weapon;
	}

	@Column(name = "quantity", nullable = false)
	public short getQuantity() {
		return this.quantity;
	}

	public void setQuantity(short quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 29)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
