package com.mok.entity;
// Generated 2015. 11. 25 ���� 7:29:01 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WeaponMaterialId generated by hbm2java
 */
@Embeddable
public class WeaponMaterialId implements java.io.Serializable {

	private int idfWeapon;
	private int idfWeaponMaterial;

	public WeaponMaterialId() {
	}

	public WeaponMaterialId(int idfWeapon, int idfWeaponMaterial) {
		this.idfWeapon = idfWeapon;
		this.idfWeaponMaterial = idfWeaponMaterial;
	}

	@Column(name = "idf_weapon", nullable = false)
	public int getIdfWeapon() {
		return this.idfWeapon;
	}

	public void setIdfWeapon(int idfWeapon) {
		this.idfWeapon = idfWeapon;
	}

	@Column(name = "idf_weapon_material", nullable = false)
	public int getIdfWeaponMaterial() {
		return this.idfWeaponMaterial;
	}

	public void setIdfWeaponMaterial(int idfWeaponMaterial) {
		this.idfWeaponMaterial = idfWeaponMaterial;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WeaponMaterialId))
			return false;
		WeaponMaterialId castOther = (WeaponMaterialId) other;

		return (this.getIdfWeapon() == castOther.getIdfWeapon())
				&& (this.getIdfWeaponMaterial() == castOther.getIdfWeaponMaterial());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdfWeapon();
		result = 37 * result + this.getIdfWeaponMaterial();
		return result;
	}

}
